name: Scala CI

on:
  push:
    branches: [ main, CI , FileIO]
  pull_request:
    branches: [ main, CI , FileIO]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Install sbt (via Coursier)
        uses: coursier/setup-action@v1
        with:
          apps: sbt

      - name: Build project
        run: sbt compile

      - name: Run tests with coverage
        run: sbt -Djava.awt.headless=true clean coverage test coverageReport

      - name: Upload coverage data to Coveralls
        run: sbt coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
